version: "3.6"

services:
    app:
        image: jkaninda/nginx-php-fpm:8.2
        container_name: my-app
        restart: unless-stopped
        volumes:
            #Project root
            - ./:/var/www/html
        ports:
            - "80:80"
        networks:
            - local #if you're using networks between containers

networks:
    local:
